# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rich_func": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://richkempinski.github.io/try_nbdev2_lib/"

git_url = "https://github.com/richkempinski/try_nbdev2_lib/tree/master/"

def custom_doc_links(name): return None
